---
- name: Restart monitoring stack
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    state: present
  when: inventory_hostname in groups['monitoring']

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

- name: Restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
